### ISSUE TITLE
Why use node ?

### ISSUE THREAD

**Issue by daoluan** [bulwark-crypto/bulwark-explorer#63]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by Penple03** [comment]
can reproduce
- Version:
- Platform:
- Subsystem:

**Comment by kewagi** [comment]
@daoluan I assume you're talking about the home node? It's an easy way to host a masternode from home without compromising your privacy. For further information, I recommend you visit our [Telegram](https://t.me/bulwarkcrypto) or [Discord](https://discord.me/bulwarkcrypto) chats.

**Comment by dustinengle** [comment]
@daoluan Node was chosen because the previous and most common block explorer, Iquidus, was written in node.  Node is also simple and easy to find support/help within the community.  As our first project made from scratch, we wanted to stay with something familiar, an already proven platform and widely used API, but make some improvements on it like using modern ES6/7 and better separation between API, database, and coin node daemon services.  From personal experience, our block explorer is faster and reliable then its predecessor, I know for some coins, after communication, they have not had to restart the API for months now, which is really good in comparison.  Our current instance of the block explorer is capped at 50% performance at this time as another testament to our good choice of creating something new and open source for cryptocurrency ;)

I wanted to chime in and try to answer it with an alternative perspective of your question.  As mentioned, if any further questions please contact us in discord or our new community forum.  

Thanks for your interest.

**Comment by daoluan** [comment]
so NODE is not the only choise but it's a better choise for you at that time. Am I right?
