### ISSUE TITLE
Issues With yarn cron commands

### ISSUE THREAD

**Issue by virtopiarvn** [bulwark-crypto/bulwark-explorer#65]
Hi,

Having issues with crons run through command, example:

`yarn run cron:masternode`

Returns:

`Error: 401
    at rpc.call (/home/user/blockex/lib/rpc.js:51:18)
    at IncomingMessage.<anonymous> (/home/user/blockex/node_modules/node-bitcoin-rpc/lib/index.js:70:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Note: I am actually using this for another project which is VerticalCoin.

Daemon is running and configured like:

`rpcuser=user
rpcpassword=pass
txindex=1
daemon=1

Daemon was compiled and binaries moved to /usr/bin,also I am using snapd for node, yarn, npm. Node version is 10.13.0.

path of /scripts/cron_block.sh has been adjusted to:
`/snap/bin/node`

also tried full path:
`/home/user/snap/bin/node`

401 to me is saying there is an authorization issue but I am not sure why. The rpc info in config.js and the daemon config file match.

See something I am missing or can give me a kick in the right direction?

**Comment by dustinengle** [comment]
There may be some compatibility issues caused by the difference between `vnode` and `masternode` usage in the RPC commands.  Have you verified that https://github.com/bulwark-crypto/bulwark-explorer/blob/master/cron/masternode.js#L25 has been converted to use `vnode` and other related areas? There can also be some differences in the format returned between coins.

**Comment by virtopiarvn** [comment]
That makes sense, thanks. Will fork and get needed changes made and see if I can get it going.

**Comment by dustinengle** [comment]
No problem, anytime, thanks.
